name: event_management
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  carousel_slider: ^5.0.0
  intl: ^0.17.0
  email_validator: ^2.0.1
  provider: ^6.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/google.png
    - lib/images/apple.png
    - lib/images/
    - lib/images/jaipur.png
    - lib/images/goa.png
    - lib/images/jaisalmer.png
    - lib/images/mussorie.png
    - lib/images/coldplay.jpeg
